from django.db import models

class Museum(models.Model):
    property_name       = models.CharField(max_length=200)
    property_id         = models.IntegerField(default=0, primary_key=True)
    street_address_1    = models.CharField(max_length=200)
    street_address_2    = models.CharField(max_length=200)
    city                = models.CharField(max_length=200)
    state               = models.CharField(max_length=200)
    other_state         = models.CharField(max_length=200)
    postal_code         = models.IntegerField(default=0)
    country             = models.CharField(max_length=200)
    year_built          = models.IntegerField(default=0)
    type                = models.CharField(max_length=200)
    construction_status = models.CharField(max_length=200)
    gross_floor_area    = models.IntegerField(default=0)
    gfa_units           = models.CharField(max_length=200)
    occupancy           = models.IntegerField(default=0)
    number_of_buildings = models.CharField(max_length=200)
    no_of_building      = models.IntegerField(default=0)

class Usage(models.Model):
    u_id                    = models.IntegerField(default=0, primary_key=True)
    property_name           = models.CharField(max_length=200)
    property_id             = models.IntegerField(default=0)
    meter_id                = models.IntegerField(default=0)
    meter_name              = models.CharField(max_length=200)
    meter_type              = models.CharField(max_length=200)
    meter_consumption_id    = models.IntegerField(default=0)
    start_date              = models.CharField(max_length=200)
    end_date                = models.CharField(max_length=200)
    delivery_date           = models.CharField(max_length=200)
    quantity                = models.FloatField()
    quantity_units          = models.CharField(max_length=200)
    cost                    = models.CharField(max_length=200)
    estimation              = models.CharField(max_length=200)
    demand                  = models.CharField(max_length=200)
    demand_cost             = models.CharField(max_length=200)
    last_modified_date      = models.CharField(max_length=200)
    last_modified_by        = models.CharField(max_length=200)
    age                     = models.FloatField(null=True)
    common_usage_units      = models.FloatField()
    date                    = models.CharField(max_length=200)
    units                   = models.CharField(max_length=200)
    usage_per_sq_feet       = models.FloatField()

class Weather(models.Model):
    date                    = models.CharField(primary_key=True, max_length=20)
    temperature             = models.FloatField()
    location                = models.CharField(max_length=35)
    elevation               = models.FloatField()
    latitude                = models.FloatField()
    longitude               = models.FloatField()


class Prediction(models.Model):
    u_id                    = models.IntegerField(default=0, primary_key=True)
    date                    = models.CharField(max_length=20)
    property_name           = models.CharField(max_length=200)
    property_id             = models.IntegerField(default=0)
    meter_type              = models.CharField(max_length=50)
    temperature             = models.FloatField()