# Generated by Django 4.2.7 on 2023-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('date', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('location', models.CharField(max_length=35)),
                ('elevation', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='usage',
            name='age',
            field=models.FloatField(null=True),
        ),
    ]
