# Generated by Django 4.2.7 on 2023-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='id',
        ),
        migrations.AddField(
            model_name='usage',
            name='u_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
